"""Add es_con_peso and tipo_banda to ejercicios

Revision ID: 2ece1435d32d
Revises: 334d85db9cef
Create Date: 2026-08-20 14:00:41.511979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ece1435d32d'
down_revision: Union[str, Sequence[str], None] = '334d85db9cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('es_con_peso', sa.Boolean(), nullable=True))
    op.add_column('ejercicios', sa.Column('tipo_banda', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ejercicios', 'tipo_banda')
    op.drop_column('ejercicios', 'es_con_peso')
    # ### end Alembic commands ###
