"""Add evaluations models

Revision ID: a0f3d86ebe46
Revises: c41cfbd124f6
Create Date: 2026-08-25 15:26:23.668868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f3d86ebe46'
down_revision: Union[str, Sequence[str], None] = 'c41cfbd124f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composicion_corporal',
    sa.Column('id_composicion', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('porcentaje_grasa', sa.Float(), nullable=True),
    sa.Column('porcentaje_musculo', sa.Float(), nullable=True),
    sa.Column('porcentaje_agua', sa.Float(), nullable=True),
    sa.Column('masa_osea', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('perimetro_pecho', sa.Float(), nullable=True),
    sa.Column('perimetro_cintura', sa.Float(), nullable=True),
    sa.Column('perimetro_cadera', sa.Float(), nullable=True),
    sa.Column('perimetro_brazo_d', sa.Float(), nullable=True),
    sa.Column('perimetro_brazo_i', sa.Float(), nullable=True),
    sa.Column('perimetro_pierna_d', sa.Float(), nullable=True),
    sa.Column('perimetro_pierna_i', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_composicion')
    )
    op.create_index(op.f('ix_composicion_corporal_id_alumno'), 'composicion_corporal', ['id_alumno'], unique=False)
    op.create_table('evaluaciones_fisicas',
    sa.Column('id_evaluacion', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cuadriceps_d', sa.Float(), nullable=True),
    sa.Column('cuadriceps_i', sa.Float(), nullable=True),
    sa.Column('isquios_d', sa.Float(), nullable=True),
    sa.Column('isquios_i', sa.Float(), nullable=True),
    sa.Column('sj_cm', sa.Float(), nullable=True),
    sa.Column('cmj_cm', sa.Float(), nullable=True),
    sa.Column('abalakov_cm', sa.Float(), nullable=True),
    sa.Column('cmj_potencia_w', sa.Float(), nullable=True),
    sa.Column('flexibilidad_cm', sa.Float(), nullable=True),
    sa.Column('push_ups_45s', sa.Integer(), nullable=True),
    sa.Column('sit_ups_45s', sa.Integer(), nullable=True),
    sa.Column('rm_sentadilla', sa.Float(), nullable=True),
    sa.Column('rm_banco', sa.Float(), nullable=True),
    sa.Column('rm_peso_muerto', sa.Float(), nullable=True),
    sa.Column('rm3_sentadilla', sa.Float(), nullable=True),
    sa.Column('rm3_banco', sa.Float(), nullable=True),
    sa.Column('rm3_peso_muerto', sa.Float(), nullable=True),
    sa.Column('peso_rir3', sa.Float(), nullable=True),
    sa.Column('peso_rir5', sa.Float(), nullable=True),
    sa.Column('cooper_m', sa.Float(), nullable=True),
    sa.Column('plancha_s', sa.Integer(), nullable=True),
    sa.Column('dominadas_reps', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_index(op.f('ix_evaluaciones_fisicas_id_alumno'), 'evaluaciones_fisicas', ['id_alumno'], unique=False)
    op.create_table('progreso_visual',
    sa.Column('id_progreso', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('url_frente', sa.String(), nullable=True),
    sa.Column('url_perfil', sa.String(), nullable=True),
    sa.Column('url_espalda', sa.String(), nullable=True),
    sa.Column('visible_para_entrenador', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_progreso')
    )
    op.create_index(op.f('ix_progreso_visual_id_alumno'), 'progreso_visual', ['id_alumno'], unique=False)
    op.add_column('alumnos', sa.Column('frecuencia_evaluacion_dias', sa.Integer(), nullable=True))
    op.add_column('alumnos', sa.Column('ultima_evaluacion_fecha', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'ultima_evaluacion_fecha')
    op.drop_column('alumnos', 'frecuencia_evaluacion_dias')
    op.drop_index(op.f('ix_progreso_visual_id_alumno'), table_name='progreso_visual')
    op.drop_table('progreso_visual')
    op.drop_index(op.f('ix_evaluaciones_fisicas_id_alumno'), table_name='evaluaciones_fisicas')
    op.drop_table('evaluaciones_fisicas')
    op.drop_index(op.f('ix_composicion_corporal_id_alumno'), table_name='composicion_corporal')
    op.drop_table('composicion_corporal')
    # ### end Alembic commands ###
