"""Add trial period to Entrenador

Revision ID: c41cfbd124f6
Revises: 2ece1435d32d
Create Date: 2026-08-21 17:56:35.534609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41cfbd124f6'
down_revision: Union[str, Sequence[str], None] = '2ece1435d32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('en_periodo_prueba', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('entrenadores', sa.Column('fecha_fin_prueba', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenadores', 'fecha_fin_prueba')
    op.drop_column('entrenadores', 'en_periodo_prueba')
    # ### end Alembic commands ###

